import type { ConformanceCase, Group } from './cases.ts'
import type { CaseReport, EngineReport, GroupReport } from './execute.ts'
import { execFileSync } from 'node:child_process'
import { arch, platform } from 'node:os'
import { repositoryRoot } from '../integration/cli-harness.ts'
import { conformanceDifferences } from '../integration/engine-differences.ts'
import { proofFiles } from '../integration/engine-expectations.ts'
import { conformanceCases, groups } from './cases.ts'
import { engineNames, engines } from './engines.ts'
import { describe, exitText } from './execute.ts'

// Writes `docs/compatibility/conformance.md`: the fixed cases by engine, with the result each engine gave, each run's
// exit, and every difference from a declared outcome in words. An engine that did not run shows as not verified, or as
// failing the gate when nothing excused it, in every cell, never as a pass.

/** Where the generated table goes, relative to the repository root. */
export const reportPath = 'docs/compatibility/conformance.md'

/** The Markdown of the table for these engine reports, one per engine in the order of `engines`. */
export function renderReport(reports: readonly EngineReport[], generatedAt: Date): string {
  const byEngine = new Map(reports.map((report) => [report.engine, report]))
  const ordered = engines.flatMap((engine) => {
    const report = byEngine.get(engine)
    return report === undefined ? [] : [report]
  })
  return [
    '# Conformance on Chrome, Firefox and WebKit',
    '',
    'Generated by `node --conditions=retest-source tests/conformance/run.ts` from the fixed list in `tests/conformance/cases.ts`. Do not edit it by hand: run the command again.',
    '',
    'Each case is a test in a file under `fixtures/conformance/`, run through the command line from its folder\'s own config, or a fact about one whole run, and each has the outcome it must end with. A failure names the operation it failed at, an action\'s command or an assertion\'s matcher, and its class, and a workflow case also the step, the line and the message of its check. Facts beside an outcome check what the outcome alone cannot show, such as what the task app received, what the page heard after a refused action, and a deadline waited in full. A case whose meaning rests on another differs when that one does. The workflow cases F1.1 to F10.5 are those of `docs/compatibility/workflow-cases.md`, with the facts their Chromium integration files check. A cell gives the result the engine gave; **differs** marks one that is not the declared outcome, and the differences are listed under the tables. An engine that did not run is never counted as passing: it is not verified when `RETEST_CONFORMANCE_OPT_OUT` names it or 0.1.0 does not support it on this platform, and otherwise it fails the gate.',
    '',
    'The cases cover the first release\'s browser scope: navigation, locators, actions, assertions, test structure, basic configuration, sign-in state, participants with their own accounts, scheduling and failure handling. AI checks and diagnostic output are in that scope too, and have fixtures of their own for each engine.',
    '',
    'An engine that refuses an operation by name, or whose browser does something Chrome\'s does not, ends a case otherwise only where `tests/integration/engine-differences.ts` declares it, with the outcome it gives, why, and the item of the engine\'s page in `docs/compatibility/` that records it. Such a case is held to that outcome exactly, and is marked **declared** in its cell; the declarations are listed under the tables. Chrome declares nothing.',
    '',
    `Generated ${generatedAt.toISOString()} on ${platform()} ${arch()}, Node ${process.versions.node}, Retest ${ordered.find((report) => report.retestVersion !== undefined)?.retestVersion ?? 'unknown'} at commit ${commit()}.`,
    '',
    '## Engines',
    '',
    '| Engine | Available | Browsers the runs launched | Cases as declared |',
    '| --- | --- | --- | --- |',
    ...ordered.map(engineRow),
    '',
    '## Cases',
    '',
    `| Case | Area | Test | Declared | ${ordered.map((report) => engineNames[report.engine]).join(' | ')} |`,
    `| --- | --- | --- | --- | ${ordered.map(() => '---').join(' | ')} |`,
    ...conformanceCases.map((each) => caseRow(each, ordered)),
    '',
    '## Runs',
    '',
    `| Run | Folder | Declared exit | ${ordered.map((report) => engineNames[report.engine]).join(' | ')} |`,
    `| --- | --- | --- | ${ordered.map(() => '---').join(' | ')} |`,
    ...groups.map((group) => groupRow(group, ordered)),
    '',
    '## Declared differences',
    '',
    '| Engine | Case | Declared outcome | Why | Recorded in |',
    '| --- | --- | --- | --- | --- |',
    ...conformanceDifferences.map((each) => `| ${engineNames[each.engine]} | ${each.case} | ${cell(describe(each.outcome))} | ${cell(each.reason)} | \`${proofFiles[each.engine]}\`, Engine differences ${each.documented.item} |`),
    '',
    '## Differences',
    '',
    ...ordered.flatMap(differences),
  ].join('\n')
}

function engineRow(report: EngineReport): string {
  const name = engineNames[report.engine]
  if (report.error !== undefined) return `| ${name} | the run failed: ${cell(report.error)} | | not judged |`
  if (!report.availability.available) return `| ${name} | ${report.availability.excused ? 'not verified' : 'no, which fails the gate'}: ${cell(report.availability.reason)} | | not run |`
  const browsers = report.browsers.map((browser) => `${browser.product} ${browser.version} (\`${browser.executablePath}\`)`).join('; ')
  const asDeclared = report.cases.filter((each) => each.differences.length === 0).length
  const runsAsDeclared = report.groups.filter((group) => group.problems.length === 0).length
  const notes = report.notes === undefined ? '' : ` ${report.notes.join(' ')}`
  return `| ${name} | yes${cell(notes)} | ${cell(browsers)} | ${asDeclared} of ${report.cases.length} cases; ${runsAsDeclared} of ${report.groups.length} runs |`
}

function caseRow(each: ConformanceCase, reports: readonly EngineReport[]): string {
  const test = each.kind === 'test' ? `\`${groupFolder(each.group)}/${each.file}\` › ${each.test}${each.variant === undefined ? '' : ` (${each.variant})`}` : `Run \`${each.group}\`: ${each.summary}`
  const declared = each.kind === 'test' ? describe(each.outcome) : 'holds'
  return `| ${each.id} | ${each.area} | ${cell(test)} | ${cell(declared)} | ${reports.map((report) => cell(given(report, each.id))).join(' | ')} |`
}

function given(report: EngineReport, id: string): string {
  if (report.error !== undefined) return 'not judged'
  if (!report.availability.available) return notRunCell(report)
  const found = report.cases.find((each) => each.id === id)
  if (found === undefined) return 'not judged'
  const given = found.declared === true ? `${found.given}, **declared**` : found.given
  return found.differences.length === 0 ? given : `${given}, **differs**`
}

function groupRow(group: Group, reports: readonly EngineReport[]): string {
  const cells = reports.map((report) => {
    if (report.error !== undefined) return 'not judged'
    if (!report.availability.available) return notRunCell(report)
    const found = report.groups.find((each) => each.group === group.name)
    return found === undefined ? 'not run' : groupCell(found)
  })
  return `| ${group.name} | \`${group.folder}\` | ${group.exitCode} | ${cells.map(cell).join(' | ')} |`
}

function groupCell(group: GroupReport): string {
  const exit = group.exit === undefined ? 'no exit' : exitText(group.exit)
  const time = group.durationMs === undefined ? '' : `, ${(group.durationMs / 1000).toFixed(1)} s`
  return group.problems.length === 0 ? `${exit}${time}` : `${exit}${time}, **differs**`
}

function differences(report: EngineReport): string[] {
  const heading = `### ${engineNames[report.engine]}`
  if (report.error !== undefined) return [heading, '', `The run failed before every case was judged: ${report.error}`, '']
  if (!report.availability.available) return [heading, '', `${report.availability.excused ? 'Not verified' : 'Did not run, which fails the gate'}: ${report.availability.reason}`, '']
  const runs = report.groups.filter((group) => group.problems.length > 0).map((group) => `- Run \`${group.group}\`: ${group.problems.join(' ')}`)
  const cases = report.cases.filter((each) => each.differences.length > 0).map((each) => `- ${each.id} (${caseName(each)}): ${each.differences.join(' ')}`)
  const lines = [...runs, ...cases]
  return [heading, '', ...(lines.length === 0 ? ['None: every case and every run ended as declared.'] : lines), '']
}

// A cell of an engine that did not run: never a pass.
function notRunCell(report: EngineReport): string {
  return report.availability.available ? 'not judged' : report.availability.excused ? 'not verified' : '**not run**'
}

function caseName(report: CaseReport): string {
  const found = conformanceCases.find((each) => each.id === report.id)
  if (found === undefined) return report.id
  return found.kind === 'test' ? found.test : found.summary
}

function groupFolder(name: string): string {
  return groups.find((group) => group.name === name)?.folder ?? name
}

/** A table cell: one line, with its pipes escaped. */
function cell(text: string): string {
  return text.replaceAll('\n', ' ').replaceAll('|', '\\|')
}

// The commit the run's source came from, and whether the tree held changes beyond it, which the run also ran.
function commit(): string {
  try {
    const git = (args: readonly string[]): string => execFileSync('git', args, { cwd: repositoryRoot, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
    const head = git(['rev-parse', '--short', 'HEAD'])
    return git(['status', '--porcelain']) === '' ? head : `${head} with uncommitted changes`
  } catch {
    return 'unknown'
  }
}

/** How many cases and runs of an engine's report did not end as declared. */
export function engineDifferences(report: EngineReport): number {
  return report.cases.filter((each) => each.differences.length > 0).length + report.groups.filter((group) => group.problems.length > 0).length
}
